### ISSUE TITLE
question about paper and score

### ISSUE THREAD

**Issue by charwing10** [tinyRattar/CSMRI_0325#1]
Hi,

Thanks for sharing the code and all the resources. It really helps me to learn and understand the paper. However, there is some problems that confused me. Could you help me?
1) In paper section 4.3, "These networks are trained with 30% random Cartesian mask" but another sentence  "Figure  7  gives  an  example  from  testing  set  with a 15%  sampling  rate, indicating that network with TDC result in less reconstruction error." My question what rate does the network use to train and test? 30% or 15%.
2) Is default.ini the setting you reported in the paper? I tried to run with this setting. After training for only 10 epoch, I got a score around PSNR 54.92, SSIM 0.9512, which is much higher than the score in the paper.
Can you give me more information about these questions? Thanks a lot!

**Comment by tinyRattar** [comment]
Hello,
Thanks for your attention!

Sampling rate is one of the pre-defined options. You can take 15%/30%(or other) sampling rate as you like. 
As for the paper, I mean section 4.3, we take two experiments. One is in 30% while the other is in 15%. Figure 6 is the qualitative result from 30% sampling rate and Figure 7 show the visual result from 15%, as the difference in detail reconstruction is more obviously.
I'm sorry it confused you. Maybe I should not announce the sampling rate in the first paragraph but announce  it with Figure 6.

default.ini should be the setting I reported, while the result is not regular. I will retrain the network and tell you later if I found anything.

Thanks.

**Comment by tinyRattar** [comment]
Okay...

I retrained with default.ini. After 10 epochs the PSNR reached 33.40, which is a normal value.
So... 
Would you like to tell me more information so I can reproduce the problem?

Thanks a lot.

**Comment by charwing10** [comment]
I guess I found the problem. Line 157 and 158 in core.py:
 psnrBefore = psnr(y2,img1,12)
 psnrAfter = psnr(y2,img2,12)

The data range 12 is related to the FastMRI dataset, not the cardiac dataset. Am I correct?

**Comment by tinyRattar** [comment]
Yes!
Thank you for pointing out!

By the way, the data range is estimated by myself, so I'm not sure it is right or not.

And I set the data range to default(1) now.
Thanks again!
