### ISSUE TITLE
NAN when tested with cs ratio 15

### ISSUE THREAD

**Issue by chuan1093** [tinyRattar/CSMRI_0325#2]
When I test with `cs ratio 15`, I found the output of the network is `NAN`. (While with cs ratio 5 or 10 or 30, it works well)

I change the `default.ini` by setting:
```
datatype = 1in1_complex_static_rand15
path = result/sampling_rate_15/CN_dOri_c5_complex_tr_trick2
```
The test code in main.py is:
```
import core as core
import numpy as np
import sys

if __name__ == '__main__':
	assert len(sys.argv)>1, "Need config name"
	configName = sys.argv[1]
	filename = 'config/'+configName+'.ini'

	c = core.core(filename, True)
	c.loadCkpt(1000, True)
	result = c.validation()
```
I guess there's something wrong with the record provided in the folder `result/sampling_rate_15`. 

Can you give me more information about this question? Thanks a lot!

**Comment by chuan1093** [comment]
By the way, are the records you gave in this [repository](https://github.com/tinyRattar/CDDNwithTDC_storage/tree/master/result) trained on **3000** cardiac MR images? or **reduced 600** cardiac MR images?  

And how to represent that datatype in config file? Taking cs ratio 10 as an example, is it `1in1_complex_static_rand10`?

Thanks for answering my questions!

**Comment by WenyiQu** [comment]
I came up with the same question and have no idea...

**Comment by tinyRattar** [comment]
try use 
`c.loadCkpt(970, False)`
to load the checkpoint 970epoch instead.

I checked the log and noticed that the network crash in last 30 epochs.
such phenomenon is not usual, maybe retrain can help.

I'm sorry for late reply (because of COVID-19)
